export const MAINTENANCE_MODE = import.meta.env.VITE_MAINTENANCE_MODE === 'true'
export const MAINTENANCE_MESSAGE = import.meta.env.VITE_MAINTENANCE_MESSAGE || ''
export const BLOCKISSUE_AUTOMATIC_MODE = import.meta.env.VITE_BLOCKISSUE_AUTOMATIC_MODE === 'true'
export const BLOCKISSUE_MESSAGE = import.meta.env.VITE_BLOCKISSUE_MESSAGE || ''
export const BLOCKISSUE_FORCE_STALE = import.meta.env.VITE_BLOCKISSUE_FORCE_STALE === 'true'
